# Generated by Django 5.2.5 on 2025-11-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.TextField()),
                ('Lastname', models.TextField()),
                ('department', models.TextField()),
                ('availability', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.TextField()),
                ('room_type', models.TextField()),
                ('building', models.TextField()),
                ('capacity', models.IntegerField()),
                ('availability', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section_Code', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('day_of_week', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursesection')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.professor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.room')),
            ],
        ),
    ]
