# Generated by Django 5.2.5 on 2025-12-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesection',
            old_name='Section_Code',
            new_name='section_code',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
