# Generated by Django 5.2.5 on 2025-12-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_professor_user_alter_professor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
