# Generated by Django 5.2.5 on 2025-12-09 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_professor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmeeting',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.roomrequest'),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='course_section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.coursesection'),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='day_of_week',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.professor'),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.room'),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='status',
            field=models.TextField(default='Pending'),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='timestamp',
            field=models.DateTimeField(default='2025-12-01 00:00'),
        ),
    ]
