# Generated by Django 5.2.5 on 2025-12-09 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_classmeeting_request_course_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursesection'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.professor'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.room'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
