# Generated by Django 5.2.5 on 2025-12-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_roomrequest_course_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrequest',
            name='denial_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classmeeting',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20),
        ),
    ]
