# Generated by Django 5.2.5 on 2025-12-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_roomrequest_denial_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmeeting',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.roomrequest'),
        ),
    ]
