# Generated by Django 6.0 on 2025-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_classmeeting_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='availability',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab'), ('Seminar', 'Seminar'), ('Auditorium', 'Auditorium')], max_length=20),
        ),
    ]
