# Generated by Django 6.0 on 2025-12-10 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_room_availability_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmeeting',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.roomrequest'),
        ),
    ]
